language: objective-c
osx_image: xcode7
xcode_project: fizzbuzz-swift.xcodeproj
xcode_scheme: fizzbuzz-swift-test
script:
  # xctool currently broken
  - xcodebuild -project fizzbuzz-swift.xcodeproj -scheme fizzbuzz-swift-test test
